### ISSUE TITLE
[Bug]: crashes with rendering banner and rendering Dread Knight

### ISSUE THREAD

**Issue by AlexMaudov** [AlexModGuy/Ice_and_Fire#4814]
### What happened?

When I teleport to Mausoleum or crafting banner with pattern from this mod, my game crash

Crash-report (banner): [crash-2023-03-28_19.49.42-client.txt](https://github.com/AlexModGuy/Ice_and_Fire/files/11092021/crash-2023-03-28_19.49.42-client.txt)
Crash-report (dread knight): [crash-2023-03-28_20.27.18-client.txt](https://github.com/AlexModGuy/Ice_and_Fire/files/11092026/crash-2023-03-28_20.27.18-client.txt)

logs: 
[latest.log](https://github.com/AlexModGuy/Ice_and_Fire/files/11092100/latest.log)
[2023-03-28-1.log](https://github.com/AlexModGuy/Ice_and_Fire/files/11092101/2023-03-28-1.log)

### Minecraft Version

1.18

### Ice and Fire version

iceandfire-2.1.12-1.18.2-SNAPSHOT+build.2023-03-22

### Citadel version

citadel-1.11.3-1.18.2

### Other Information

- [X] I am using other mods besides Ice and Fire
- [x] I have attached a log file from the session that I have experienced this issue

**Comment by TheBv** [comment]
Could you try crafting a banner with some of the patterns from ice and fire?
And if that works apply it to a shield?
I'm struggling to find what could be the issue here and my gut feeling would be a mod dependency issue rn...

**Comment by AlexMaudov** [comment]
> Could you try crafting a banner with some of the patterns from ice and fire? And if that works apply it to a shield? I'm struggling to find what could be the issue here and my gut feeling would be a mod dependency issue rn...
I made a banner with patterns from Ice&Fire that time. It didn't crash with vanilla patterns, only with Ice&Fire patterns

**Comment by TheBv** [comment]
Same as #4779
Closing/moving discussion to over there
