### ISSUE TITLE
[Bug]: Staring weapon of mobs affect the Warden despite it is legally blind.

### ISSUE THREAD

**Issue by pantsguyapp** [AlexModGuy/Ice_and_Fire#5143]
### What happened?

Cockatrices and Gorgon can damage the warden with their stare, but the warden couldn't see and it detect them by smell.

### Minecraft Version

1.20.2

### Ice and Fire version

iceandfire-2.1.13-1.20.1-beta-2

### Citadel version

citadel-2.5.2-1.20.1

### Other Information

- [ ] I am using other mods besides Ice and Fire
- [X] I have attached a log file from the session that I have experienced this issue

**Comment by TheBv** [comment]
Fixed with #5107
